UPDATE FS_TB001_FUSEI_RELEASE T
   SET T.RELIEVE_STATUS     = T.STATUS,
       T.STATUS             = '0',
       T.STATUS_UPDATE_DATE = TO_CHAR(SYSDATE, 'YYYYMMDD'),
       T.UPD_SEL_DATE       = TO_CHAR(SYSDATE, 'YYYYMMDD')
 WHERE NOT EXISTS
      (SELECT NULL FROM FS_TB005_NEW_FUSEI_&1 M
        WHERE M.SVR_GRP_ID       = T.SVR_GRP_ID
          AND M.SVR_ID           = T.SVR_ID
          AND M.HONGW_DSTSK_PATH = T.HONGW_DSTSK_PATH
          AND M.KNRBKKN_FILE_ID  = T.KNRBKKN_FILE_ID )
   AND T.SVR_KBN = '&1'
   AND T.STATUS <> '0'
   AND (T.SVR_GRP_ID,T.SVR_ID) IN (SELECT N.SVR_GRP_ID,N.SVR_ID FROM FS_TB006_SVR_JOUHOU N WHERE N.NEW_COMPARE_FLAG = '1' AND N.SVR_KBN = '&1' );
COMMIT;
