@create_user.sql	ASAITI_PAST_0000
@create_user.sql	ASAITI_PAST_0001
@create_user.sql	ASAITI_PAST_0002
@create_user.sql	ASAITI_PAST_0003
@create_user.sql	ASAITI_PAST_1000
@create_user.sql	ASAITI_PAST_10001
@create_user.sql	ASAITI_PAST_2000
@create_user.sql	ASAITI_PAST_USER
@create_user.sql	ASAITI_TODAY_0000
@create_user.sql	ASAITI_TODAY_0001
@create_user.sql	ASAITI_TODAY_0002
@create_user.sql	ASAITI_TODAY_0003
@create_user.sql	ASAITI_TODAY_1000
@create_user.sql	ASAITI_TODAY_10001
@create_user.sql	ASAITI_TODAY_2000
@create_user.sql	ASAITI_TODAY_USER
@create_user.sql	SIMEGO_PAST_1000
@create_user.sql	SIMEGO_PAST_10001
@create_user.sql	SIMEGO_PAST_2000
@create_user.sql	SIMEGO_PAST_USER
@create_user.sql	SIMEGO_TODAY_1000
@create_user.sql	SIMEGO_TODAY_10001
@create_user.sql	SIMEGO_TODAY_2000
@create_user.sql	SIMEGO_TODAY_USER
@create_user.sql	TMP_MASK_DB1
@create_user.sql	TMP_MASK_DB10
@create_user.sql	TMP_MASK_DB2
@create_user.sql	TMP_MASK_DB3
@create_user.sql	TMP_MASK_DB4
@create_user.sql	TMP_MASK_DB5
@create_user.sql	TMP_MASK_DB6
@create_user.sql	TMP_MASK_DB7
@create_user.sql	TMP_MASK_DB8
@create_user.sql	TMP_MASK_DB9
@create_user.sql	MASK_SYS
