INSERT INTO FS_TB005_NEW_FUSEI_&1
  SELECT A.SVR_GRP_ID AS SVR_GRP_ID,
         A.SVR_ID AS SVR_ID,
         A.HONGW_DSTSK_PATH AS HONGW_DSTSK_PATH,
         A.KNRBKKN_FILE_ID AS KNRBKKN_FILE_ID,
         'T' AS COMPARE_FLAG,
         C.KNRBKKN_TIMESTAMP AS ELIBSYS_KNRBKKN_TIMESTAMP,
         C.KNRBKKN_SIZE AS ELIBSYS_KNRBKKN_SIZE,
         C.HON_REP_LIBTHM_ID AS ELIBSYS_HON_REP_LIBTHM_ID,
         A.KNRBKKN_TIMESTAMP AS HONBAN_KNRBKKN_TIMESTAMP,
         A.KNRBKKN_SIZE AS HONBAN_KNRBKKN_SIZE,
         A.CHECK_SUM AS HONBAN_CHECK_SUM,
         '1' AS ERROR_TYPE
    FROM FS_TB003_MODULE_&1 A,
         FS_TB007_OLD_MODULE_&1 B,
         FS_TB004_MODULE_ELIB_&1 C
   WHERE A.SVR_GRP_ID = B.SVR_GRP_ID
     AND A.SVR_ID = B.SVR_ID
     AND A.HONGW_DSTSK_PATH = B.HONGW_DSTSK_PATH
     AND A.KNRBKKN_FILE_ID = B.KNRBKKN_FILE_ID
     AND A.KNRBKKN_TIMESTAMP = B.KNRBKKN_TIMESTAMP
     AND A.KNRBKKN_SIZE = B.KNRBKKN_SIZE
     AND A.CHECK_SUM <> B.CHECK_SUM
     AND A.SVR_GRP_ID = C.SVR_GRP_ID
     AND A.SVR_ID = C.SVR_ID
     AND A.HONGW_DSTSK_PATH = C.HONGW_DSTSK_PATH
     AND A.KNRBKKN_FILE_ID = C.KNRBKKN_FILE_ID
     AND A.KNRBKKN_TIMESTAMP = C.KNRBKKN_TIMESTAMP
     AND A.KNRBKKN_SIZE = C.KNRBKKN_SIZE;
COMMIT;
