INSERT INTO FS_TB004_MODULE_ELIB_&1
  SELECT T.SVR_GRP_ID,
         M.SVR_ID,
         T.HONGW_DSTSK_PATH,
         T.KNRBKKN_FILE_ID,
         T.KNRBKKN_TIMESTAMP,
         T.KNRBKKN_SIZE,
         T.HON_REP_LIBTHM_ID
    FROM FS_TB002_MODULE_ELIB T, FS_TB006_SVR_JOUHOU M
   WHERE T.SVR_GRP_ID = M.SVR_GRP_ID
     AND M.SVR_KBN = '&1'
     AND M.NEW_COMPARE_FLAG = '1';
